// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzSWBejGSMNjHaFZUbTveI1_IBBCf2k48',
    appId: '1:316060077139:web:d776d3d674954e6384caa6',
    messagingSenderId: '316060077139',
    projectId: 'weatherapp-flutter-track',
    authDomain: 'weatherapp-flutter-track.firebaseapp.com',
    storageBucket: 'weatherapp-flutter-track.appspot.com',
    measurementId: 'G-C6ZRWLWTDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQiIbsHl_zlovcTKoLy9lIHoZwHPD4yU',
    appId: '1:316060077139:android:4e4a58cfcd8668d684caa6',
    messagingSenderId: '316060077139',
    projectId: 'weatherapp-flutter-track',
    storageBucket: 'weatherapp-flutter-track.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB8uSxM5lKYu602NUg7oDHpoOX8ud9NP8',
    appId: '1:316060077139:ios:e3ba82882243337c84caa6',
    messagingSenderId: '316060077139',
    projectId: 'weatherapp-flutter-track',
    storageBucket: 'weatherapp-flutter-track.appspot.com',
    iosClientId: '316060077139-gl3fnp06b0c7poqal30qgtjkap2iituk.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather1App',
  );
}
